### ISSUE TITLE
Error TS2304: Cannot find name '$' in summernote.component.ts 

### ISSUE THREAD

**Issue by richarepo** [carlescs/ng2-alt-summernote#2]
I am getting following errors on npm start

ERROR in <project path>\node_modules\ng2-alt-summernote\src\summernote.component.ts
(44,13): error TS2304: Cannot find name '$'.
Same error comes at following locations as well:
(73,9): error TS2304: Cannot find name '$'.
(97,9): error TS2304: Cannot find name '$'.

ERROR in <project path>\node_modules\ng2-alt-summernote\src\summernote.component.ts
(103,9): error TS2304: Cannot find name 'jQuery'.

I am using 
Angular 2.4.2
Bootstrap 3.3.7
Summernote 0.8.2
Jquery 3.1.1
ng2-bootstrap 1.1.16

Can you pls confirm how to solve it ?

**Comment by richarepo** [comment]
Solved it by using default exports
declare var $: JQuery;
declare var jQuery: any;

but Now I am getting error *Uncaught SyntaxError: Unexpected token export* from
```export {SummernoteComponent} from './src/summernote.component';```
in ng2-alt-summernote/index.ts, in console while running in browser.

**Comment by carlescs** [comment]
Hi,
I did some changes yesterday to make it more compliant with angular2 Modules best practices (export js with d.ts.file to NPM basically), but I broke the build. I'll take a look this afternoon to fix it.

For now, as a workaround, you can copy the summernote.component.ts file to your project and import it directly to your NgModule.

Thanks trying it out. Also, if you know how to fix it, a PR is obviously welcome.

**Comment by carlescs** [comment]
Ok. Made some changes and it's now working with Webpack. Need to review angular-cli deploy now.

I'll add explanation to make it work with plaint Webpack in the README.

Can you check if your problem is fixed with version 0.1.0?

Thanks!

**Comment by carlescs** [comment]
I added the updated explanation for angular-cli and for webpack in the README. Hope it helps with you issue.
