### ISSUE TITLE
codeView option shows blank screen

### ISSUE THREAD

**Issue by richarepo** [carlescs/ng2-alt-summernote#5]
Summernote codeView option shows blank screen. I have installed latest codemirror and ng2-alt-summernote. This is also not working on testAngular code. I have taken latest code and checked.
Can you pls confirm how can i edit my HTML contents in it ?

**Comment by carlescs** [comment]
I've reproduced the issue. If I'm not mistaken you need to include codemirror.css to be able to see the code correctly. I've fixed it in testangular by adding the css to `angular-cli.json`. If you're using webpack directly just import the css file. Hope this helps.
