### ISSUE TITLE
Missing Typescript files generate warning

### ISSUE THREAD

**Issue by topaxi** [carlescs/ng2-alt-summernote#8]
As the NPM module is not shipping the Typescript files, bundlers and compilers which respect sourcemaps generate warnings (as the original files are referenced in the sourcemaps).

I'd suggest to ship the original Typescript files through NPM too.

Another option would be to inline the original source in the sourcemap files or exclude the sourcemaps.

**Comment by carlescs** [comment]
I released a new version including the .ts files. Can you, please, confirm if the issue is fixed?

Thanks!

**Comment by topaxi** [comment]
Works like a charm, thanks!
