### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by richarepo** [carlescs/ng2-alt-summernote#9]
Hi 

When I fresh install all packages I am getting _Unexpected token export_ in browser console and no error in webpack, and my client is not working. I am using latest version of ng2-alt-summernote with webpack.

Please provide a solution so that I can make my app working.

**Comment by carlescs** [comment]
I think this is related to issue #8. I'll inline the sources in the sourcemap and remove the .ts files from the npm package.

**Comment by carlescs** [comment]
Hi @richarepo,
Was the issue fixed with the latest release? Or do you still experience it?

Thanks!

**Comment by richarepo** [comment]
No, I am still getting same issue. Webpack is giving no error and in browser when I open it gives _Unexpected token export_ error.

**Comment by carlescs** [comment]
I could not reproduce it. I added another minimal example [here](https://github.com/carlescs/test-ng2-alt-summernote). Are you sure the problem is with my component?

**Comment by carlescs** [comment]
If you can provide a failing sample, please reopen the issue.

Thanks.
